# Generated by Django 3.1.5 on 2021-01-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMailColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=2083, unique=True)),
                ('title', models.CharField(max_length=2083)),
                ('columnist', models.CharField(max_length=2083)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
